name: Create PulsBridge Unity Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: create unitypackage from files
        uses: natsuneko-laboratory/create-unitypackage@v3
        with:
          files: |
            ./Assets/Plugins/PulsBridge.jslib
            ./Assets/Puls/PulsBridge.cs
            ./Assets/WebGLTemplates/PulsTemplate/index.HTML
          dest: test.unitypackage

      - name: create unitypackage from glob pattern
        uses: natsuneko-laboratory/create-unitypackage@v3
        with:
          files-glob: |
            ./Assets/NatsunekoLaboratory/**/*.cs
          dest: test.unitypackage
