name: CreateUnityPackage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  create-package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Verify files exist
      run: |
        ls Assets/Plugins/PulsBridge.jslib || exit 1
        ls Assets/Puls/PulsBridge.cs || exit 1
        ls Assets/WebGLTemplates/PulsTemplate/index.html || exit 1
        
    - name: Create UnityPackage
      id: create-pkg
      uses: game-ci/unity-actions/create-unitypackage@v0.1
      with:
        files: |
          Assets/Plugins/PulsBridge.jslib
          Assets/Puls/PulsBridge.cs
          Assets/WebGLTemplates/PulsTemplate/index.html
        package-name: 'PulsBridgeSDK'
        output-path: 'Packages'
        version: '1.0.${{ github.run_number }}'
        
    - name: Verify package created
      run: ls Packages/PulsBridgeSDK.1.0.${{ github.run_number }}.unitypackage || exit 1
        
    - name: Upload Artifact
      if: steps.create-pkg.outcome == 'success'
      uses: actions/upload-artifact@v3
      with:
        name: PulsBridgeSDK.unitypackage
        path: Packages/PulsBridgeSDK.1.0.${{ github.run_number }}.unitypackage
