name: Create PulsBridge Unity Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история для корректной работы

      - name: Verify files exist
        run: |
          ls ./Assets/Plugins/PulsBridge.jslib || exit 1
          ls ./Assets/Puls/PulsBridge.cs || exit 1
          ls ./Assets/WebGLTemplates/PulsTemplate/index.html || exit 1

      - name: Create Builds directory
        run: mkdir -p build
      
      - name: Create unitypackage
        id: create-pkg
        uses: natsuneko-laboratory/create-unitypackage@v3
        with:
          files: |
            Assets/Plugins/PulsBridge.jslib
            Assets/Puls/PulsBridge.cs
            Assets/WebGLTemplates/PulsTemplate/index.html
          dest: ./build/PulsBridgeSDK.1.0.${{ github.run_number }}.unitypackage

      - name: Verify package creation
        run: |
          ls -la build/
          test -f build/PulsBridgeSDK.1.0.${{ github.run_number }}.unitypackage || exit 1

      - name: Upload artifact
        if: steps.create-pkg.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: PulsBridgeSDK
          path: build/PulsBridgeSDK.1.0.${{ github.run_number }}.unitypackage
