name: Create PulsBridge Unity Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Generate meta file list
      run: |
        echo "Assets/Plugins/PulsBridge.jslib.meta" > metaList
        echo "Assets/Puls/PulsBridge.cs.meta" >> metaList
        echo "Assets/WebGLTemplates/PulsTemplate/index.html.meta" >> metaList
        find Assets/Plugins/ -name PulsBridge* >> metaList
        find Assets/Puls/ -name PulsBridge* >> metaList
        find Assets/WebGLTemplates/PulsTemplate/ -type f >> metaList
        
    - name: Create Packages directory
      run: mkdir -p Packages
    
    - name: Create Unity Package
      uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'Packages/PulsBridgeSDK.1.0.${{ github.run_number }}.unitypackage'
        include-files: metaList
    
    - name: Upload Package Artifact
      uses: actions/upload-artifact@master
      with:
        path: Packages/PulsBridgeSDK.1.0.${{ github.run_number }}.unitypackage
        name: PulsBridge-UnityPackage
