name: Create PulsBridge Unity Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify files exist
        run: |
          ls ./Assets/Plugins/PulsBridge.jslib || exit 1
          ls ./Assets/Puls/PulsBridge.cs || exit 1
          ls ./Assets/WebGLTemplates/PulsTemplate/index.html || exit 1

      - name: Create Builds directory
        run: mkdir -p build
      
      - name: Create unitypackage manually
        run: |
          UNITY_PACKAGE=build/PulsBridgeSDK.1.0.${{ github.run_number }}.unitypackage
          mkdir -p temp_pkg
          cp -r Assets/Plugins/PulsBridge.jslib temp_pkg/
          cp -r Assets/Puls/PulsBridge.cs temp_pkg/
          cp -r Assets/WebGLTemplates/PulsTemplate temp_pkg/
          zip -r $UNITY_PACKAGE temp_pkg/
          rm -rf temp_pkg
